# Generated by Django 4.2.11 on 2024-09-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer_name",
            new_name="customer",
        ),
    ]
